version: "3"

services:
 api:
  container_name: test-server
  build:
   context: .
   dockerfile: Dockerfile.local
   args:
    ENV_PATH: "config-dev.toml"
  volumes:
   - .:/app
  ports:
   - "9090:9090"
  command: ["air"]
  environment:
   GO_ENV: 'dev'
 mariadb:
  container_name: mariadb
  image: mariadb:10.11.7
  command: --innodb-flush-method=O_DSYNC --innodb-use-native-aio=0 --log_bin=ON
  ports:
   - 3306:3306
  environment:
   MYSQL_ROOT_USER: ${DB_ROOT_USERNAME}
   MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
   MYSQL_USER: ${DB_USERNAME}
   MYSQL_PASSWORD: ${DB_PASSWORD}
   MYSQL_DATABASE: ${DB_NAME}
  volumes:
   - ${DB_LOCAL_PATH}:/var/lib/mysql
   - ./tools/mysql/init.d:/docker-entrypoint-initdb.d
